version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i yarn@latest -g
  build:
    commands:
      - cd app
      - yarn install
      - yarn build
      - cd ..
      - yarn install
      - yarn add serverless -g
  post_build:
    commands:
      - serverless --stage prod deploy
