version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.8
    commands:
      - npm i npm@latest -g
      - pip install awscli
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - npm run build
    post_build:
      commands:
        - npm run deploy
