version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i yarn@latest -g
  build:
    commands:
      # Triggering a build
      - cd app
      - yarn install
      - yarn build
      - cd ..
      - yarn install
      - yarn run serverless --stage prod deploy
