---
service:
  name: recipecrate

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-export-env
  - serverless-s3-sync

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  timeout: 30
  runtime: nodejs10.x
  resourceGroup: recipecrate
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  region: ${opt:region, 'us-east-1'}
  environment:

custom:
  accountId:
    local: '000000000000'
    mockdev: '#{AWS::AccountId}'
    dev: '#{AWS::AccountId}'
    prod: '#{AWS::AccountId}'
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  s3Sync:
    - bucketName: ${self:provider.stage}-recipecrate-site-bucket
      localDir: app/build
      acl: public-read
      defaultContentType: text/html
      params:
        - index.html:
          CacheControl: 'no-cache'
        - "*.js":
          CacheControl: 'public, max-age=31536000'
functions:

resources:
  Resources: ${file(./resources-${self:provider.stage}.yml)}
