service:
  name: recipecrate

plugins:
  - serverless-offline
  - serverless-export-env
  - serverless-plugin-export-endpoints
  - serverless-webpack

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
  region: ${opt:region, 'us-east-1'}

  custom:
    webpack:
      includeModules:
        forceExclude: aws-sdk

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  Resources:
  Output: